src/Entity/Task.php
<?php

namespace App\Entity;

use DateTimeInterface;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\TaskRepository;
use DateTime;
use phpDocumentor\Reflection\Types\Boolean;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\TaskRepository")
 * @ORM\Table
 */
class Task
{
    /**
     * @var Int
     *
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @var DateTimeInterface
     *
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @var String
     *
     * @ORM\Column(type="string")
     * @Assert\NotBlank(message="Vous devez saisir un titre.")
     */
    private $title;

    /**
     * @var String
     *
     * @ORM\Column(type="text")
     * @Assert\NotBlank(message="Vous devez saisir du contenu.")
     */
    private $content;

    /**
     * @var bool
     *
     * @ORM\Column(type="boolean")
     */
    private $isDone;

    /**
     * @var User
     *
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="tasks")
     * @ORM\JoinColumn(nullable=true)
     */
    private $Author;

    /**
     * __construct Task Class
     */
    public function __construct()
    {
        $this->createdAt = new \Datetime();
        $this->isDone = false;
    }

    /**
     * @return Int|null
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return DateTimeInterface|null
     */
    public function getCreatedAt(): ?DateTimeInterface
    {
        return $this->createdAt;
    }

    /**
     * @param DateTimeInterface $createdAt
     * @return void
     */
    public function setCreatedAt(DateTimeInterface $createdAt): void
    {
        $this->createdAt = $createdAt;
    }

    /**
     * @return String|null
     */
    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle($title)
    {
        $this->title = $title;
    }

    /**
     * @return String|null
     */
    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent($content)
    {
        $this->content = $content;
    }

    /**
     * @return bool
     */
    public function isDone(): bool
    {
        return $this->isDone;
    }

    /**
     * @param boolean $flag
     * @return void
     */
    public function toggle(bool $flag): void
    {
        $this->isDone = $flag;
    }

    /**
     * @return User|null
     */
    public function getAuthor(): ?User
    {
        return $this->Author;
    }

    public function setAuthor(?User $Author): self
    {
        $this->Author = $Author;

        return $this;
    }
}

src/Form/TaskType.php
<?php

namespace App\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;

class TaskType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title')
            ->add('content', TextareaType::class)
        ;
    }
}

src/Controller/TaskController.php
<?php

namespace App\Controller;

use App\Entity\Task;
use App\Form\TaskType;
use App\Repository\TaskRepository;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

class TaskController extends AbstractController
{
    /**
     * list all Tasks
     *
     * @Route("/tasks", name="task_list")
     *
     * @return Response
     */
    public function list(): Response
    {
        return $this->render(
            'task/list.html.twig',
            ['tasks' => $this->getDoctrine()->getRepository('App:Task')->findAll()]
        );
    }

    /**
     * Create new task
     *
     * @Route("/tasks/create", name="task_create")
     *
     * @param Request $request
     * @return Response
     */
    public function create(Request $request): Response
    {
        $task = new Task();
        $form = $this->createForm(TaskType::class, $task);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $task->setAuthor($this->getUser());
            $em->persist($task);
            $em->flush();

            $this->addFlash('success', 'La tâche a bien été ajoutée.');

            return $this->redirectToRoute('task_list');
        }

        return $this->render('task/create.html.twig', ['form' => $form->createView()]);
    }

    /**
     * edit a Task
     *
     * @Route("/tasks/{id}/edit", name="task_edit", methods={"GET", "POST"})
     *
     * @param $id
     * @param Request $request
     * @return Response
     */
    public function edit(Task $task, Request $request, TaskRepository $taskRepository): Response
    {
        $form = $this->createForm(TaskType::class, $task);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();
            $this->addFlash('success', 'La tâche a bien été modifiée.');
            return $this->redirectToRoute('task_list');
        }

        return $this->render('task/edit.html.twig', [
            'form' => $form->createView(),
            'task' => $task,
        ]);
    }

    /**
     * Toogle task function
     *
     * @Route("/tasks/{id}/toggle", name="task_toggle")
     *
     * @param Task $task
     * @return Response
     */
    public function toggleTask(Task $task): Response
    {
        $task->toggle(!$task->isDone());
        $this->getDoctrine()->getManager()->flush();

        if ($task->isDone()) {
            $flash = sprintf('La tâche %s a bien été marquée comme faite.', $task->getTitle());
        } else {
            $flash = sprintf('La tâche %s a bien été marquée comme non terminée.', $task->getTitle());
        }

        $this->addFlash('success', sprintf($flash, $task->getTitle()));

        return $this->redirectToRoute('task_list');
    }

    /**
     * Delete a task
     *
     * @Route("/tasks/{id}/delete", name="task_delete")
     *
     * @param Task $task
     * @return Response
     */
    public function deleteTask(Task $task): Response
    {
        $this->denyAccessUnlessGranted('DELETE', $task, 'Vous n\'êtes pas autorisé à supprimer cette tâche.');

        $em = $this->getDoctrine()->getManager();
        $em->remove($task);
        $em->flush();

        $this->addFlash('success', 'La tâche a bien été supprimée.');

        return $this->redirectToRoute('task_list');
    }
}

templates/task/create.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="row">
        {{ form_start(form, {'action' : path('task_create')}) }}
            {{ form_widget(form) }}

            <button type="submit" class="btn btn-success pull-right">Ajouter</button>
        {{ form_end(form) }}

        <a href="{{ path('task_list') }}" class="btn btn-primary">Retour à la liste des tâches</a>
    </div>
{% endblock %}

templates/task/edit.html.twig
{% extends 'base.html.twig' %}

{% block body %}
	<div class="row">
		{{ form_start(form) }}
		{{ form_widget(form) }}

		<button type="submit" class="btn btn-success pull-right">Modifier</button>
		{{ form_end(form) }}
	</div>
{% endblock %}

templates/task/list.html.twig
{% extends 'base.html.twig' %}

{% block header_img %}<img class="slide-image" src="{{ asset('assets/img/todolist_content.jpg') }}" alt="todo list">
{% endblock %}

{% block body %}
	<a href="{{ path('task_create') }}" class="btn btn-info pull-right">Créer une tâche</a>
	<div class="row">
		{% for task in tasks %}
			<div class="col-sm-4 col-lg-4 col-md-4">
				<div class="thumbnail">
					<div class="caption">
						<h4 class="pull-right">
							{% if task.isDone %}
								<span class="glyphicon glyphicon-ok"></span>
							{% else %}
								<span class="glyphicon glyphicon-remove"></span>
							{% endif %}
						</h4>
						<h4>
							<a href="{{ path('task_edit', {'id' : task.id }) }}">{{ task.title }}</a>
						</h4>
						<p>{{ task.content }}</p>
						{% if task.author %}
							<p>Auteur :
								{{ task.author.username }}</p>
						{% else %}
							<p>Auteur : Anonyme</p>
						{% endif %}
					</div>
					<div>
						<form action="{{ path('task_toggle', {'id' : task.id }) }}">
							<button class="btn btn-success btn-sm pull-right">
								{% if not task.isDone %}Marquer comme faite{% else %}Marquer non terminée
								{% endif %}
							</button>
						</form>
						<form action="{{ path('task_delete', {'id' : task.id }) }}">
							<button class="btn btn-danger btn-sm pull-right">Supprimer</button>
						</form>
					</div>
				</div>
			</div>
		{% else %}
			<div class="alert alert-warning" role="alert">
				Il n'y a pas encore de tâche enregistrée.
				<a href="{{ path('task_create') }}" class="btn btn-warning pull-right">Créer une tâche</a>
			</div>
		{% endfor %}
	</div>
{% endblock %}